# Generated by Django 4.2.7 on 2023-11-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0002_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='userName',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default='mohammed.xafeer@gmail.com', max_length=254),
        ),
    ]
