# Generated by Django 4.2.7 on 2023-11-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0003_remove_login_username_login_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='passWord',
            new_name='password',
        ),
    ]
